# frozen_string_literal: true

# Auto-loaded by factory_bot_rails from test/factories.rb.
# Seed data (roles, permissions) is loaded once in test_helper.rb — these
# factories cover per-test data only.

FactoryBot.define do
  # ── Users ─────────────────────────────────────────────────────────────────

  factory :user do
    sequence(:email) { |n| "user#{n}@example.com" }
    password              { "Password1!" }
    first_name            { "Test" }
    last_name             { "User" }
    kind                  { "merchant_user" }
    otp_required_for_login { false }

    # user_code is generated by before_create callback — no need to set here.
  end

  # Separate named factories so callers read clearly: create(:merchant_user)
  # vs create(:internal_staff_user) — avoids hidden trait coupling.

  factory :merchant_user, parent: :user do
    kind { "merchant_user" }
    sequence(:email) { |n| "merchant#{n}@example.com" }

    # Create an active membership so User#merchant_code works immediately.
    after(:create) do |user|
      create(:merchant_membership, user: user, invited_by: nil)
    end
  end

  factory :internal_staff_user, parent: :user do
    kind { "internal_staff" }
    sequence(:email) { |n| "staff#{n}@yagye.com" }
    # Internal staff have no merchant membership.
  end

  # ── Merchant memberships ──────────────────────────────────────────────────

  factory :merchant_membership do
    association :user
    merchant_code { "MCH-#{SecureRandom.hex(4).upcase}" }
    merchant_name { "Test Merchant Ltd" }
    state         { "active" }
    invited_by    { nil }
  end

  # ── User roles ─────────────────────────────────────────────────────────────
  # Role keys must match seeds. The default is a merchant role + merchant user.

  factory :user_role do
    association :user, factory: :merchant_user
    role_key    { "merchant_owner" }
    granted_at  { Time.current }
    granted_by  { nil }
    merchant_code { user.merchant_code }

    trait :ops_analyst do
      association :user, factory: :internal_staff_user
      role_key      { "ops_analyst" }
      merchant_code { nil }
    end

    trait :compliance_manager do
      association :user, factory: :internal_staff_user
      role_key      { "compliance_manager" }
      merchant_code { nil }
    end
  end

  # ── Portal merchant applications ──────────────────────────────────────────

  factory :portal_merchant_application do
    application_code { "APP-#{SecureRandom.hex(4).upcase}" }
    merchant_code    { "MCH-#{SecureRandom.hex(4).upcase}" }
    legal_name       { "Test Merchant Ltd" }
    trading_name     { "Test Merchant" }
    country          { "GH" }
    status           { "under_review" }
    last_applied_at  { Time.current }
    last_event_id    { SecureRandom.uuid }
  end
end
